# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_uploadphoneno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadphoneno',
            name='phoneno',
            field=models.IntegerField(),
        ),
    ]
