# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 15:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_auto_20180121_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('By_name', models.CharField(default='user', max_length=150)),
                ('to_name', models.CharField(default='user', max_length=150)),
                ('requested_by_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_created', to=settings.AUTH_USER_MODEL)),
                ('requested_to_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
