# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 16:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_requests'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_by_name', models.CharField(default='user', max_length=150)),
                ('date', models.DateTimeField(default='1999-01-01 01:01:01')),
                ('liked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=150)),
                ('title', models.TextField(max_length=150)),
                ('post', models.TextField()),
                ('date', models.DateTimeField(default='')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_by_name', models.CharField(default='user', max_length=150)),
                ('date', models.DateTimeField(default='1999-01-01 01:01:01')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_by', to=settings.AUTH_USER_MODEL)),
                ('shared_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_post', to='app.Posts')),
            ],
        ),
        migrations.AddField(
            model_name='likes',
            name='liked_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_post', to='app.Posts'),
        ),
    ]
