# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180121_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='date',
        ),
    ]
