# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_likes_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shares',
            name='date',
        ),
    ]
