# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_shares_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='id',
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.TextField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
