# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_auto_20180122_0023'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together=set([('liked_by', 'liked_by_name', 'liked_post')]),
        ),
        migrations.AlterUniqueTogether(
            name='shares',
            unique_together=set([('shared_by', 'shared_by_name', 'shared_post')]),
        ),
    ]
